import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header'
import styles from '../styles/Blog.module.css'

import { titleToUrl } from '../utils'

const Home: NextPage = () => {

  const posts = [
    { title: 'Post title 1', description: 'post description 1 bla bla bla bla something here to fill it out but we have to write a lot of thing the way that we can find aas much as i can write shit here because i need to test the line clamp alright i already wrote a lot but i will keep writing some more nothing just to', date: '17 September 2021' },
  ]

  return (
    <div className='container'>
      <Head>
        <title>@joaovitorzv • blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <main className={styles.main}>
        {posts.map(post => (
          <section key={post.title} className={styles.post}>
            <Link href={`/post/${titleToUrl(post.title)}`}>
              <a className={styles.postTitle}>{post.title}</a>
            </Link> 
            <span>{post.date}</span>
            <p>{post.description}</p>
            <Link href={`/post/${titleToUrl(post.title)}`}>continue reading</Link>
          </section>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>Copyright &copy; {"\"new Date().getFullYear()\""} João Vitor Veras </p>
      </footer>
    </div>
  )
}

export default Home
